---
inherit: base.yml
applications:
- name: crime-data-explorer-master
  host: crime-data-explorer-master
  buildpack: nodejs_buildpack
  memory: 256M
  disk_quota: 256M
  domain: fr.cloud.gov
env:
  CDE_API: 'https://crime-data-api-master.fr.cloud.gov'
  NEW_RELIC_APP_NAME: 'crime-data-frontend-master'
services:
  - crime-data-api-key-development
