---
inherit: base.yml
applications:
- name: crime-data-explorer
  host: crime-data-explorer
  buildpack: nodejs_buildpack
  memory: 512M
  domain: fr.cloud.gov
  instances: 2
env:
  CDE_API: 'https://api.usa.gov/crime/fbi/ucr'
  NEW_RELIC_APP_NAME: 'crime-data-frontend-production'
services:
  - crime-data-api-key-production
